= CDC Warsaw JUG code

This repository contains code for the Warsaw JUG meeting. It contains
the consumer and the producer applications to use with Spring Cloud Contract
project.

== Projects

=== Beer-contracts

Contains the repo with all contracts for all applications. It can be used
when you want to store all contracts in a single place.

=== Producer

The producer application contains contracts for both REST and messaging
communication. From these contracts tests and stubs will be generated.

=== Producer_with_external_contracts

The producer application that downloads its contracts for both REST and messaging
communication, from the `Beer-contracts` JAR. From these contracts tests and stubs will be generated.

=== Consumer

The consumer application is using the stubs of the producer for both
rest and messaging.

== How to build it?

You can run Maven from the root folder

[source,bash]
----
./mvnw clean install
----

The order should be as follows

- beer-contracts
- producer
- producer_with_external_contracts
- consumer

If the order is different then your apps will blow up most likely due to missing stubs.

You can also go to each of the projects and run Gradle wrapper:

[source,bash]
----
./gradlew clean build publishToMavenLocal
----